package config

func baseSchema() []SectionSchema {
	return []SectionSchema{
		{
			ID:          "api",
			Label:       "API",
			Description: "Conversation model and API credentials.",
			Fields: []FieldSchema{
				{Path: "api.default_model", Label: "Default Model", Description: "Default provider.model id used by new sessions, such as anthropic.sonnet.", Type: "string", LiveApply: true, Env: "GODEX_API_DEFAULT_MODEL"},
				{Path: "api.providers", Label: "LLM Providers", Description: "JSON/YAML object keyed by provider id. Each provider declares type/base_url/api_key/timeout_seconds and nested supported models.", Type: "json", Secret: true, LiveApply: true},
				{Path: "api.model_strategy", Label: "Model Strategy", Description: "JSON/YAML strategy controlling runtime model selection. Supported type values: primary, fallback, round_robin.", Type: "json", LiveApply: true},
				{Path: "api.default_profile", Label: "Legacy Default Profile", Description: "Legacy selectable profile id. Prefer api.default_model for provider.model ids.", Type: "string", LiveApply: true, Env: "GODEX_API_DEFAULT_PROFILE"},
				{Path: "api.auto_fallback_enabled", Label: "Auto Fallback Enabled", Description: "Allow automatic provider/model fallback for retryable model-call failures.", Type: "bool", LiveApply: true, Env: "GODEX_API_AUTO_FALLBACK_ENABLED"},
				{Path: "api.timeout_seconds", Label: "Timeout Seconds", Description: "Total timeout for one model request. Increase this for long-running streamed answers.", Type: "int", LiveApply: true, Env: "GODEX_API_TIMEOUT_SECONDS"},
			},
		},
		{
			ID:          "acp",
			Label:       "ACP Agents",
			Description: "External Agent Client Protocol agents callable through the acp_agent tool.",
			Fields: []FieldSchema{
				{Path: "acp.agents", Label: "ACP Agents", Description: "JSON/YAML object keyed by agent id. Each agent supports command/args/env/timeout_seconds/description.", Type: "json", Secret: true, LiveApply: true},
			},
		},
		{
			ID:          "agent",
			Label:       "Agent",
			Description: "Conversation and compression tuning.",
			Fields: []FieldSchema{
				{Path: "agent.compress_threshold", Label: "Compress Threshold", Description: "Approximate threshold before auto-compaction becomes worthwhile.", Type: "int", LiveApply: true, Env: "COMPRESS_THRESHOLD"},
				{Path: "agent.compaction.auto_enabled", Label: "Auto Compaction", Description: "Enable automatic fast compaction before context gets too large.", Type: "bool", LiveApply: true, Env: "GODEX_AGENT_COMPACTION_AUTO_ENABLED"},
				{Path: "agent.compaction.trigger_tokens", Label: "Compaction Trigger Tokens", Description: "Estimated token threshold that triggers fast history compaction.", Type: "int", LiveApply: true, Env: "GODEX_AGENT_COMPACTION_TRIGGER_TOKENS"},
				{Path: "agent.compaction.target_history_tokens", Label: "Target History Tokens", Description: "Target estimated history budget after fast compaction.", Type: "int", LiveApply: true, Env: "GODEX_AGENT_COMPACTION_TARGET_HISTORY_TOKENS"},
				{Path: "agent.compaction.mode", Label: "Compaction Mode", Description: "Default compaction mode for manual and background compaction.", Type: "string", LiveApply: true, Env: "GODEX_AGENT_COMPACTION_MODE", Options: []string{"fast", "model", "hybrid"}},
				{Path: "agent.compaction.model_profile_id", Label: "Compaction Model Profile", Description: "Optional model profile used only for explicit model or hybrid compaction.", Type: "string", LiveApply: true, Env: "GODEX_AGENT_COMPACTION_MODEL_PROFILE_ID"},
				{Path: "agent.compaction.max_latency_ms", Label: "Compaction Max Latency Ms", Description: "Latency budget for compaction diagnostics and model fallback decisions.", Type: "int", LiveApply: true, Env: "GODEX_AGENT_COMPACTION_MAX_LATENCY_MS"},
				{Path: "agent.max_turns", Label: "Max Turns", Description: "Maximum model/tool loop iterations for one main-agent turn.", Type: "int", LiveApply: true, Env: "GODEX_AGENT_MAX_TURNS"},
				{Path: "agent.profile", Label: "Agent Profile", Description: "Default agent capability profile for channels without a specific override.", Type: "string", LiveApply: true, Env: "GODEX_AGENT_PROFILE", Options: []string{"general", "coding"}},
				{Path: "agent.default_profiles.acp", Label: "ACP Default Profile", Description: "Default agent profile for ACP/IDE sessions.", Type: "string", LiveApply: true, Env: "GODEX_AGENT_DEFAULT_PROFILE_ACP", Options: []string{"coding", "general"}},
				{Path: "agent.default_profiles.cli", Label: "CLI Default Profile", Description: "Default agent profile for CLI ask and readline sessions.", Type: "string", LiveApply: true, Env: "GODEX_AGENT_DEFAULT_PROFILE_CLI", Options: []string{"coding", "general"}},
				{Path: "agent.default_profiles.tui", Label: "TUI Default Profile", Description: "Default agent profile for terminal UI sessions.", Type: "string", LiveApply: true, Env: "GODEX_AGENT_DEFAULT_PROFILE_TUI", Options: []string{"coding", "general"}},
				{Path: "agent.default_profiles.web", Label: "Web Default Profile", Description: "Default agent profile for Web UI sessions.", Type: "string", LiveApply: true, Env: "GODEX_AGENT_DEFAULT_PROFILE_WEB", Options: []string{"general", "coding"}},
				{Path: "agent.default_profiles.weixin", Label: "Weixin Default Profile", Description: "Default agent profile for Weixin channel sessions.", Type: "string", LiveApply: true, Env: "GODEX_AGENT_DEFAULT_PROFILE_WEIXIN", Options: []string{"general", "coding"}},
				{Path: "agent.default_profiles.feishu", Label: "Feishu Default Profile", Description: "Default agent profile for Feishu/Lark channel sessions.", Type: "string", LiveApply: true, Env: "GODEX_AGENT_DEFAULT_PROFILE_FEISHU", Options: []string{"general", "coding"}},
			},
		},
		{
			ID:          "logging",
			Label:       "Logging",
			Description: "Logger output, level, and mirror behavior.",
			Fields: []FieldSchema{
				{Path: "logging.level", Label: "Level", Description: "Minimum severity to emit.", Type: "string", LiveApply: true, Env: "LOG_LEVEL", Options: []string{"debug", "info", "warn", "error"}},
				{Path: "logging.file_path", Label: "File Path", Description: "Log file path. Relative paths resolve under GODEX_HOME.", Type: "string", LiveApply: true, Env: "LOG_FILE"},
				{Path: "logging.also_stderr", Label: "Mirror To Stderr", Description: "When enabled, file logging also mirrors to stderr.", Type: "bool", LiveApply: true, Env: "LOG_MIRROR_TO_STDERR"},
			},
		},
		{
			ID:          "web",
			Label:       "Web",
			Description: "Built-in Web UI and HTTP API configuration.",
			Fields: []FieldSchema{
				{Path: "web.token", Label: "Shared Bearer Token", Description: "Protects chat and config HTTP APIs.", Type: "string", Secret: true, LiveApply: true, Env: "GODEX_WEB_TOKEN"},
			},
		},
		{
			ID:          "cron",
			Label:       "Cron",
			Description: "Persistent scheduler defaults for automation jobs.",
			Fields: []FieldSchema{
				{Path: "cron.enabled", Label: "Enabled", Description: "Enable the background cron scheduler in serve mode.", Type: "bool", LiveApply: true, Env: "GODEX_CRON_ENABLED"},
				{Path: "cron.tick_seconds", Label: "Tick Seconds", Description: "Scheduler polling interval in seconds.", Type: "int", LiveApply: true, Env: "GODEX_CRON_TICK_SECONDS"},
				{Path: "cron.default_timezone", Label: "Default Timezone", Description: "Default timezone used by cron jobs that do not set one explicitly.", Type: "string", LiveApply: true, Env: "GODEX_CRON_DEFAULT_TIMEZONE"},
				{Path: "cron.max_concurrent_runs", Label: "Max Concurrent Runs", Description: "Maximum number of cron jobs that may execute concurrently.", Type: "int", LiveApply: true, Env: "GODEX_CRON_MAX_CONCURRENT_RUNS"},
			},
		},
		{
			ID:          "heartbeat",
			Label:       "Heartbeat",
			Description: "Background proactive checklist defaults.",
			Fields: []FieldSchema{
				{Path: "heartbeat.enabled", Label: "Enabled", Description: "Enable the background heartbeat loop in serve mode.", Type: "bool", LiveApply: true, Env: "GODEX_HEARTBEAT_ENABLED"},
				{Path: "heartbeat.tick_seconds", Label: "Tick Seconds", Description: "Heartbeat polling interval in seconds.", Type: "int", LiveApply: true, Env: "GODEX_HEARTBEAT_TICK_SECONDS"},
				{Path: "heartbeat.checklist_path", Label: "Checklist Path", Description: "Default HEARTBEAT.md path.", Type: "string", LiveApply: true, Env: "GODEX_HEARTBEAT_CHECKLIST_PATH"},
				{Path: "heartbeat.ok_token", Label: "OK Token", Description: "Suppress delivery when heartbeat output contains this token.", Type: "string", LiveApply: true, Env: "GODEX_HEARTBEAT_OK_TOKEN"},
				{Path: "heartbeat.default_interval_seconds", Label: "Default Interval Seconds", Description: "Default interval used by the heartbeat rule.", Type: "int", LiveApply: true, Env: "GODEX_HEARTBEAT_DEFAULT_INTERVAL_SECONDS"},
				{Path: "heartbeat.default_timezone", Label: "Default Timezone", Description: "Default timezone used by heartbeat scheduling.", Type: "string", LiveApply: true, Env: "GODEX_HEARTBEAT_DEFAULT_TIMEZONE"},
			},
		},
		{
			ID:          "control",
			Label:       "Control Plane",
			Description: "Runtime node identity, central registration, and heartbeat settings.",
			Fields: []FieldSchema{
				{Path: "control.node_name", Label: "Node Name", Description: "Human-readable name for this Godex runtime in the control plane.", Type: "string", Env: "GODEX_CONTROL_NODE_NAME"},
				{Path: "control.center_url", Label: "Center URL", Description: "Optional central Godex service URL for auto-registration and heartbeat.", Type: "string", Env: "GODEX_CONTROL_CENTER_URL"},
				{Path: "control.heartbeat_seconds", Label: "Heartbeat Seconds", Description: "Node heartbeat interval when registering to a center service.", Type: "int", Env: "GODEX_CONTROL_HEARTBEAT_SECONDS"},
				{Path: "control.offline_after_seconds", Label: "Offline After Seconds", Description: "Mark a node offline after this many seconds without heartbeat.", Type: "int", Env: "GODEX_CONTROL_OFFLINE_AFTER_SECONDS"},
				{Path: "control.nodes", Label: "Manual Nodes", Description: "Optional JSON/YAML list of manually known nodes with id/name/endpoint/workspace_dir/godex_home/version/capabilities.", Type: "json"},
			},
		},
		{
			ID:          "team",
			Label:       "Team",
			Description: "Lead/team names, default skills, and teammate loop tuning.",
			Fields: []FieldSchema{
				{Path: "team.lead_name", Label: "Lead Name", Description: "Primary user/lead identity.", Type: "string", LiveApply: true, Env: "LEAD_NAME"},
				{Path: "team.team_name", Label: "Team Name", Description: "Logical team name for teammate runtime.", Type: "string", LiveApply: true, Env: "TEAM_NAME"},
				{Path: "team.default_skills", Label: "Default Skills", Description: "Skill names loaded into fresh sessions.", Type: "string_list", LiveApply: true, Env: "DEFAULT_SKILLS"},
				{Path: "team.teammate_work_limit", Label: "Teammate Work Limit", Description: "Maximum loop iterations before teammate yields.", Type: "int", LiveApply: true, Env: "TEAMMATE_WORK_ITERATIONS"},
				{Path: "team.teammate_poll_seconds", Label: "Teammate Poll Seconds", Description: "Idle polling interval for teammate inbox.", Type: "int", LiveApply: true, Env: "TEAMMATE_IDLE_POLL_INTERVAL_SECONDS"},
				{Path: "team.teammate_idle_timeout_seconds", Label: "Teammate Idle Timeout Seconds", Description: "How long a teammate can stay idle before waking.", Type: "int", LiveApply: true, Env: "TEAMMATE_IDLE_TIMEOUT_SECONDS"},
			},
		},
		{
			ID:          "runtime",
			Label:       "Runtime",
			Description: "Recovery and long-running runtime behavior.",
			Fields: []FieldSchema{
				{Path: "runtime.recovery.auto_resume_interrupted_turns", Label: "Auto Resume Interrupted Turns", Description: "Queue a recovery turn after detecting an interrupted turn on restart.", Type: "bool", LiveApply: true, Env: "GODEX_RUNTIME_RECOVERY_AUTO_RESUME_INTERRUPTED_TURNS"},
				{Path: "runtime.recovery.auto_repair_sessions", Label: "Auto Repair Sessions", Description: "Repair low-risk session JSON and checkpoint inconsistencies on startup/open.", Type: "bool", LiveApply: true, Env: "GODEX_RUNTIME_RECOVERY_AUTO_REPAIR_SESSIONS"},
			},
		},
		{
			ID:          "security",
			Label:       "Security",
			Description: "Safety profile applied to execution, approval, network, and host-privilege defaults.",
			Fields: []FieldSchema{
				{Path: "security.profile", Label: "Safety Profile", Description: "trusted-local, guarded-local, sandboxed, strict, host-privileged, or dev/repair.", Type: "string", LiveApply: true, Env: "GODEX_SECURITY_PROFILE", Options: []string{"trusted-local", "guarded-local", "sandboxed", "strict", "host-privileged", "dev/repair"}},
			},
		},
		{
			ID:          "storage",
			Label:       "Storage",
			Description: "Runtime storage retention, browser cache cleanup, and checkpoint pruning.",
			Fields: []FieldSchema{
				{Path: "storage.tmp_ttl_hours", Label: "Tmp TTL Hours", Description: "Retention hint for temporary runtime files.", Type: "int", LiveApply: true, Env: "GODEX_STORAGE_TMP_TTL_HOURS"},
				{Path: "storage.artifact_ttl_hours", Label: "Artifact TTL Hours", Description: "Default retention for manually generated artifacts and web_fetch spill files before GC.", Type: "int", LiveApply: true, Env: "GODEX_STORAGE_ARTIFACT_TTL_HOURS"},
				{Path: "storage.browser_cache_auto_clean", Label: "Browser Cache Auto Clean", Description: "Clean rebuildable Chromium cache directories before launching the local browser.", Type: "bool", LiveApply: true, Env: "GODEX_STORAGE_BROWSER_CACHE_AUTO_CLEAN"},
				{Path: "storage.browser_cache_max_mb", Label: "Browser Cache Max MB", Description: "Soft target for browser cache diagnostics.", Type: "int", LiveApply: true, Env: "GODEX_STORAGE_BROWSER_CACHE_MAX_MB"},
				{Path: "storage.session_checkpoint_keep_latest", Label: "Checkpoint Keep Latest", Description: "Number of latest checkpoints to keep per session.", Type: "int", LiveApply: true, Env: "GODEX_STORAGE_SESSION_CHECKPOINT_KEEP_LATEST"},
				{Path: "storage.session_checkpoint_ttl_hours", Label: "Checkpoint TTL Hours", Description: "Checkpoint retention window used by session GC.", Type: "int", LiveApply: true, Env: "GODEX_STORAGE_SESSION_CHECKPOINT_TTL_HOURS"},
				{Path: "storage.session_checkpoint_auto_prune", Label: "Checkpoint Auto Prune", Description: "Prune old checkpoints after writing a new checkpoint.", Type: "bool", LiveApply: true, Env: "GODEX_STORAGE_SESSION_CHECKPOINT_AUTO_PRUNE"},
				{Path: "storage.session_backend", Label: "Session Backend", Description: "Session state backend: json or sqlite.", Type: "string", LiveApply: true, Env: "GODEX_STORAGE_SESSION_BACKEND"},
				{Path: "storage.sqlite_path", Label: "SQLite Path", Description: "Optional SQLite database path for session storage.", Type: "string", LiveApply: true, Env: "GODEX_STORAGE_SQLITE_PATH"},
			},
		},
		{
			ID:          "paths",
			Label:       "Paths",
			Description: "Workspace-relative or absolute paths for Godex state.",
			Fields: []FieldSchema{
				{Path: "paths.state_dir", Label: "State Dir", Description: "Root directory for persistent Godex state.", Type: "string", LiveApply: true},
				{Path: "paths.team_dir", Label: "Team Dir", Description: "Directory for teammate runtime state.", Type: "string", LiveApply: true},
				{Path: "paths.tasks_dir", Label: "Tasks Dir", Description: "Persistent task board directory.", Type: "string", LiveApply: true},
				{Path: "paths.todos_dir", Label: "Todos Dir", Description: "Todo storage directory.", Type: "string", LiveApply: true},
				{Path: "paths.memory_dir", Label: "Memory Dir", Description: "Workspace memory storage.", Type: "string", LiveApply: true},
				{Path: "paths.rules_dir", Label: "Rules Dir", Description: "Local rules directory.", Type: "string", LiveApply: true},
				{Path: "paths.skills_dir", Label: "Skills Dir", Description: "Third-party skills directory.", Type: "string", LiveApply: true},
				{Path: "paths.mcp_config_path", Label: "MCP Config Path", Description: "MCP server config JSON path.", Type: "string", LiveApply: true},
				{Path: "paths.temp_dir", Label: "Temp Dir", Description: "Temporary runtime file directory.", Type: "string", LiveApply: true},
				{Path: "paths.transcripts_dir", Label: "Transcripts Dir", Description: "Conversation compaction archive directory.", Type: "string", LiveApply: true},
				{Path: "paths.sessions_dir", Label: "Sessions Dir", Description: "Unified session backend persistence directory.", Type: "string", LiveApply: true},
			},
		},
		{
			ID:          "tools-web-search",
			Label:       "Tools / Web Search",
			Description: "Built-in current-information search providers and cache policy.",
			Fields: []FieldSchema{
				{Path: "tools.web_search.enabled", Label: "Enabled", Description: "Enable the built-in web_search tool.", Type: "bool", LiveApply: true, Env: "GODEX_WEB_SEARCH_ENABLED"},
				{Path: "tools.web_search.provider_order", Label: "Provider Order", Description: "Comma-separated provider order. Supported: brave, exa, tavily, browser, duckduckgo.", Type: "string_list", LiveApply: true, Env: "GODEX_WEB_SEARCH_PROVIDER_ORDER"},
				{Path: "tools.web_search.cache_ttl_seconds", Label: "Cache TTL Seconds", Description: "In-memory cache lifetime for repeated searches.", Type: "int", LiveApply: true, Env: "GODEX_WEB_SEARCH_CACHE_TTL_SECONDS"},
				{Path: "tools.web_search.browser.engine", Label: "Browser Engine", Description: "Browser search engine preset: duckduckgo, bing, brave, or custom.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_ENGINE", Options: []string{"duckduckgo", "bing", "brave", "custom"}},
				{Path: "tools.web_search.browser.engine_fallback", Label: "Browser Engine Fallback", Description: "Comma-separated browser engines to try when the primary engine fails or returns no results.", Type: "string_list", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_ENGINE_FALLBACK"},
				{Path: "tools.web_search.browser.wait_network_idle_ms", Label: "Browser Search Network Idle MS", Description: "Network idle wait before extracting browser search results.", Type: "int", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_WAIT_NETWORK_IDLE_MS"},
				{Path: "tools.web_search.browser.wait_after_load_ms", Label: "Browser Search Wait After Load MS", Description: "Extra wait after navigation before extraction.", Type: "int", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_WAIT_AFTER_LOAD_MS"},
				{Path: "tools.web_search.browser.max_scrolls", Label: "Browser Search Max Scrolls", Description: "Number of scroll attempts before extracting browser search results.", Type: "int", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_MAX_SCROLLS"},
				{Path: "tools.web_search.browser.result_timeout_seconds", Label: "Browser Search Timeout Seconds", Description: "Timeout for one browser search provider request.", Type: "int", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_RESULT_TIMEOUT_SECONDS"},
				{Path: "tools.web_search.browser.preferred_hosts", Label: "Browser Search Preferred Hosts", Description: "Hosts that receive a small ranking boost in browser search results.", Type: "string_list", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_PREFERRED_HOSTS"},
				{Path: "tools.web_search.browser.engines.duckduckgo.search_url_template", Label: "DuckDuckGo Search URL", Description: "DuckDuckGo URL template. Use {{query}} for URL-encoded query. Default: https://duckduckgo.com/?q={{query}}&ia=web.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_DUCKDUCKGO_SEARCH_URL_TEMPLATE"},
				{Path: "tools.web_search.browser.engines.duckduckgo.blocked_hosts", Label: "DuckDuckGo Blocked Hosts", Description: "DuckDuckGo result hosts to filter, usually the search engine host itself. Supports *.example.com.", Type: "string_list", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_DUCKDUCKGO_BLOCKED_HOSTS"},
				{Path: "tools.web_search.browser.engines.duckduckgo.result_container_selector", Label: "DuckDuckGo Result Container Selector", Description: "Optional CSS selector for one search-result block. Demo: .result or article. Leave empty to scan visible links.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_DUCKDUCKGO_RESULT_CONTAINER_SELECTOR"},
				{Path: "tools.web_search.browser.engines.duckduckgo.result_link_selector", Label: "DuckDuckGo Result Link Selector", Description: "Optional CSS selector for title link inside each result block. Demo: .result__a or h2 a.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_DUCKDUCKGO_RESULT_LINK_SELECTOR"},
				{Path: "tools.web_search.browser.engines.duckduckgo.result_snippet_selector", Label: "DuckDuckGo Result Snippet Selector", Description: "Optional CSS selector for summary text inside each result block. Demo: .result__snippet or p.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_DUCKDUCKGO_RESULT_SNIPPET_SELECTOR"},
				{Path: "tools.web_search.browser.engines.bing.search_url_template", Label: "Bing Search URL", Description: "Bing URL template. Use {{query}} for URL-encoded query. Default: https://www.bing.com/search?q={{query}}.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_BING_SEARCH_URL_TEMPLATE"},
				{Path: "tools.web_search.browser.engines.bing.blocked_hosts", Label: "Bing Blocked Hosts", Description: "Bing result hosts to filter, usually bing.com and *.bing.com.", Type: "string_list", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_BING_BLOCKED_HOSTS"},
				{Path: "tools.web_search.browser.engines.bing.result_container_selector", Label: "Bing Result Container Selector", Description: "Optional CSS selector for one result block. Demo: li.b_algo.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_BING_RESULT_CONTAINER_SELECTOR"},
				{Path: "tools.web_search.browser.engines.bing.result_link_selector", Label: "Bing Result Link Selector", Description: "Optional CSS selector for title link inside each result. Demo: h2 a.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_BING_RESULT_LINK_SELECTOR"},
				{Path: "tools.web_search.browser.engines.bing.result_snippet_selector", Label: "Bing Result Snippet Selector", Description: "Optional CSS selector for summary text inside each result. Demo: .b_caption p.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_BING_RESULT_SNIPPET_SELECTOR"},
				{Path: "tools.web_search.browser.engines.brave.search_url_template", Label: "Brave Search URL", Description: "Brave Search URL template. Use {{query}} for URL-encoded query. Default: https://search.brave.com/search?q={{query}}&source=web.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_BRAVE_SEARCH_URL_TEMPLATE"},
				{Path: "tools.web_search.browser.engines.brave.blocked_hosts", Label: "Brave Blocked Hosts", Description: "Brave result hosts to filter, usually search.brave.com and *.search.brave.com.", Type: "string_list", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_BRAVE_BLOCKED_HOSTS"},
				{Path: "tools.web_search.browser.engines.brave.result_container_selector", Label: "Brave Result Container Selector", Description: "Optional CSS selector for one result block. Demo: div[data-testid=\"web-result\"].", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_BRAVE_RESULT_CONTAINER_SELECTOR"},
				{Path: "tools.web_search.browser.engines.brave.result_link_selector", Label: "Brave Result Link Selector", Description: "Optional CSS selector for title link inside each result. Demo: a[href].", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_BRAVE_RESULT_LINK_SELECTOR"},
				{Path: "tools.web_search.browser.engines.brave.result_snippet_selector", Label: "Brave Result Snippet Selector", Description: "Optional CSS selector for summary text inside each result. Demo: .snippet or p.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_BRAVE_RESULT_SNIPPET_SELECTOR"},
				{Path: "tools.web_search.browser.engines.custom.search_url_template", Label: "Custom Search URL", Description: "Custom browser search URL template. Use {{query}} for URL-encoded query or {{query_raw}} for raw text.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_CUSTOM_SEARCH_URL_TEMPLATE"},
				{Path: "tools.web_search.browser.engines.custom.blocked_hosts", Label: "Custom Blocked Hosts", Description: "Custom search-result hosts to filter, usually the search engine host itself. Supports *.example.com.", Type: "string_list", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_CUSTOM_BLOCKED_HOSTS"},
				{Path: "tools.web_search.browser.engines.custom.result_container_selector", Label: "Custom Result Container Selector", Description: "Optional CSS selector for one result block. Demo: .result, article, or li.search-result.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_CUSTOM_RESULT_CONTAINER_SELECTOR"},
				{Path: "tools.web_search.browser.engines.custom.result_link_selector", Label: "Custom Result Link Selector", Description: "Optional CSS selector for title link inside each result block. Demo: h2 a or a.result-title.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_CUSTOM_RESULT_LINK_SELECTOR"},
				{Path: "tools.web_search.browser.engines.custom.result_snippet_selector", Label: "Custom Result Snippet Selector", Description: "Optional CSS selector for summary text inside each result block. Demo: .snippet or p.summary.", Type: "string", LiveApply: true, Env: "GODEX_WEB_SEARCH_BROWSER_CUSTOM_RESULT_SNIPPET_SELECTOR"},
				{Path: "tools.web_search.brave.api_key", Label: "Brave API Key", Description: "Optional Brave Search API key.", Type: "string", Secret: true, LiveApply: true, Env: "GODEX_WEB_SEARCH_BRAVE_API_KEY"},
				{Path: "tools.web_search.exa.api_key", Label: "Exa API Key", Description: "Optional Exa API key.", Type: "string", Secret: true, LiveApply: true, Env: "GODEX_WEB_SEARCH_EXA_API_KEY"},
				{Path: "tools.web_search.tavily.api_key", Label: "Tavily API Key", Description: "Optional Tavily API key.", Type: "string", Secret: true, LiveApply: true, Env: "GODEX_WEB_SEARCH_TAVILY_API_KEY"},
			},
		},
		{
			ID:          "tools-web-fetch",
			Label:       "Tools / Web Fetch",
			Description: "Built-in page fetching, extraction, and domain safety policy.",
			Fields: []FieldSchema{
				{Path: "tools.web_fetch.enabled", Label: "Enabled", Description: "Enable the built-in web_fetch tool.", Type: "bool", LiveApply: true, Env: "GODEX_WEB_FETCH_ENABLED"},
				{Path: "tools.web_fetch.max_chars", Label: "Max Chars", Description: "Default maximum extracted characters before truncation/file spill.", Type: "int", LiveApply: true, Env: "GODEX_WEB_FETCH_MAX_CHARS"},
				{Path: "tools.web_fetch.timeout_seconds", Label: "Timeout Seconds", Description: "HTTP timeout for one web_fetch request.", Type: "int", LiveApply: true, Env: "GODEX_WEB_FETCH_TIMEOUT_SECONDS"},
				{Path: "tools.web_fetch.policy", Label: "Policy", Description: "allow_all or allowlist domain policy.", Type: "string", LiveApply: true, Env: "GODEX_WEB_FETCH_POLICY", Options: []string{"allow_all", "allowlist"}},
				{Path: "tools.web_fetch.allowed_domains", Label: "Allowed Domains", Description: "Comma-separated allowlist when policy=allowlist.", Type: "string_list", LiveApply: true, Env: "GODEX_WEB_FETCH_ALLOWED_DOMAINS"},
				{Path: "tools.web_fetch.blocked_domains", Label: "Blocked Domains", Description: "Comma-separated domain blocklist. Supports *.example.com.", Type: "string_list", LiveApply: true, Env: "GODEX_WEB_FETCH_BLOCKED_DOMAINS"},
				{Path: "tools.web_fetch.allow_private_hosts", Label: "Allow Private Hosts", Description: "Permit localhost and private-network fetches.", Type: "bool", LiveApply: true, Env: "GODEX_WEB_FETCH_ALLOW_PRIVATE_HOSTS"},
			},
		},
		{
			ID:          "tools-glob",
			Label:       "Tools / Glob",
			Description: "Workspace-scoped file discovery defaults.",
			Fields: []FieldSchema{
				{Path: "tools.glob.default_max_results", Label: "Default Max Results", Description: "Default maximum matches returned by glob.", Type: "int", LiveApply: true, Env: "GODEX_GLOB_DEFAULT_MAX_RESULTS"},
			},
		},
		{
			ID:          "tools-subagent",
			Label:       "Tools / Subagent",
			Description: "Durable subagent batching, concurrency, and runtime limits.",
			Fields: []FieldSchema{
				{Path: "tools.subagent.max_batch_size", Label: "Max Batch Size", Description: "Maximum subagent jobs accepted by one batch call.", Type: "int", LiveApply: true, Env: "GODEX_SUBAGENT_MAX_BATCH_SIZE"},
				{Path: "tools.subagent.max_concurrent_jobs", Label: "Max Concurrent Jobs", Description: "Maximum durable subagent jobs running concurrently.", Type: "int", LiveApply: true, Env: "GODEX_SUBAGENT_MAX_CONCURRENT_JOBS"},
				{Path: "tools.subagent.default_max_turns", Label: "Subagent Max Turns", Description: "Default and minimum turn budget for one durable subagent. Model-provided max_turns below this value are raised to this value.", Type: "int", LiveApply: true, Env: "GODEX_SUBAGENT_DEFAULT_MAX_TURNS"},
				{Path: "tools.subagent.max_job_timeout_ms", Label: "Max Job Timeout Ms", Description: "Maximum explicit per-job timeout in milliseconds. Zero disables the cap.", Type: "int", LiveApply: true, Env: "GODEX_SUBAGENT_MAX_JOB_TIMEOUT_MS"},
				{Path: "tools.subagent.readonly_isolation", Label: "Read-only Isolation", Description: "Workspace isolation for read-only subagents.", Type: "string", LiveApply: true, Env: "GODEX_SUBAGENT_READONLY_ISOLATION", Options: []string{"shared_readonly", "snapshot"}},
				{Path: "tools.subagent.git_dirty_isolation", Label: "Git Dirty Isolation", Description: "Workspace isolation for dirty Git repositories.", Type: "string", LiveApply: true, Env: "GODEX_SUBAGENT_GIT_DIRTY_ISOLATION", Options: []string{"snapshot", "dirty_overlay"}},
				{Path: "tools.subagent.non_git_write_isolation", Label: "Non-git Write Isolation", Description: "Workspace isolation for write-capable subagents outside Git repositories.", Type: "string", LiveApply: true, Env: "GODEX_SUBAGENT_NON_GIT_WRITE_ISOLATION", Options: []string{"copy_snapshot", "shared_with_approval", "deny"}},
				{Path: "tools.subagent.workspace_ttl_hours", Label: "Workspace TTL Hours", Description: "Default retention period for terminal subagent workspaces.", Type: "int", LiveApply: true, Env: "GODEX_SUBAGENT_WORKSPACE_TTL_HOURS"},
			},
		},
		{
			ID:          "tools-execution",
			Label:       "Tools / Execution",
			Description: "Backend used by bash and background command execution tools.",
			Fields: []FieldSchema{
				{Path: "tools.execution.mode", Label: "Mode", Description: "local runs on the host; docker bind-mounts the workspace into a container; ssh runs commands on a configured remote target.", Type: "string", LiveApply: true, Env: "GODEX_TOOLS_EXECUTION_MODE", Options: []string{"local", "docker", "ssh"}},
				{Path: "tools.execution.docker_image", Label: "Docker Image", Description: "Container image used when mode=docker.", Type: "string", LiveApply: true, Env: "GODEX_TOOLS_EXECUTION_DOCKER_IMAGE"},
				{Path: "tools.execution.docker_network", Label: "Docker Network", Description: "Optional Docker network name, such as none, host, bridge, or a custom network.", Type: "string", LiveApply: true, Env: "GODEX_TOOLS_EXECUTION_DOCKER_NETWORK"},
				{Path: "tools.execution.ssh_target", Label: "SSH Target", Description: "SSH target used when mode=ssh, such as user@host.", Type: "string", LiveApply: true, Env: "GODEX_TOOLS_EXECUTION_SSH_TARGET"},
				{Path: "tools.execution.ssh_workspace", Label: "SSH Workspace", Description: "Remote workspace path used when mode=ssh.", Type: "string", LiveApply: true, Env: "GODEX_TOOLS_EXECUTION_SSH_WORKSPACE"},
				{Path: "tools.execution.ssh_options", Label: "SSH Options", Description: "Extra ssh options, such as -o BatchMode=yes.", Type: "string_list", LiveApply: true, Env: "GODEX_TOOLS_EXECUTION_SSH_OPTIONS"},
				{Path: "tools.execution.shell_allow_patterns", Label: "Shell Allow Patterns", Description: "Optional command glob/prefix patterns allowed for bash/background_run. Empty means no extra allow restriction.", Type: "string_list", LiveApply: true, Env: "GODEX_TOOLS_EXECUTION_SHELL_ALLOW_PATTERNS"},
				{Path: "tools.execution.shell_deny_patterns", Label: "Shell Deny Patterns", Description: "Command glob/prefix patterns denied for bash/background_run before execution.", Type: "string_list", LiveApply: true, Env: "GODEX_TOOLS_EXECUTION_SHELL_DENY_PATTERNS"},
			},
		},
		{
			ID:          "tools-browser",
			Label:       "Tools / Browser",
			Description: "Interactive browser automation runtime for dynamic pages.",
			Fields: []FieldSchema{
				{Path: "tools.browser.enabled", Label: "Enabled", Description: "Enable the built-in browser tool.", Type: "bool", LiveApply: true, Env: "GODEX_BROWSER_ENABLED"},
				{Path: "tools.browser.headless", Label: "Headless", Description: "Launch the local browser in headless mode.", Type: "bool", LiveApply: true, Env: "GODEX_BROWSER_HEADLESS"},
				{Path: "tools.browser.browser_path", Label: "Browser Path", Description: "Optional local Chrome/Chromium binary to launch directly.", Type: "string", LiveApply: true, Env: "GODEX_BROWSER_PATH"},
				{Path: "tools.browser.cdp_url", Label: "CDP URL", Description: "Optional remote Chrome DevTools endpoint.", Type: "string", LiveApply: true, Env: "GODEX_BROWSER_CDP_URL"},
				{Path: "tools.browser.action_timeout_seconds", Label: "Action Timeout Seconds", Description: "Timeout for one browser action.", Type: "int", LiveApply: true, Env: "GODEX_BROWSER_ACTION_TIMEOUT_SECONDS"},
				{Path: "tools.browser.idle_timeout_seconds", Label: "Idle Timeout Seconds", Description: "Close idle browser pages after this many seconds.", Type: "int", LiveApply: true, Env: "GODEX_BROWSER_IDLE_TIMEOUT_SECONDS"},
				{Path: "tools.browser.max_pages_per_session", Label: "Max Pages Per Session", Description: "Maximum open browser pages tracked per Godex session.", Type: "int", LiveApply: true, Env: "GODEX_BROWSER_MAX_PAGES_PER_SESSION"},
				{Path: "tools.browser.allow_private_hosts", Label: "Allow Private Hosts", Description: "Permit localhost and private-network browser navigation.", Type: "bool", LiveApply: true, Env: "GODEX_BROWSER_ALLOW_PRIVATE_HOSTS"},
			},
		},
		{
			ID:          "tools-history-search",
			Label:       "Tools / History Search",
			Description: "Policy-driven recall of prior visible conversation snippets without writing durable memory.",
			Fields: []FieldSchema{
				{Path: "tools.history_search.enabled", Label: "Enabled", Description: "Enable the history_search capability and its policy evaluation.", Type: "bool", LiveApply: true, Env: "GODEX_TOOLS_HISTORY_SEARCH_ENABLED"},
				{Path: "tools.history_search.auto.enabled", Label: "Auto Enabled", Description: "Allow weak automatic exposure when the history recall policy score is high enough.", Type: "bool", LiveApply: true, Env: "GODEX_TOOLS_HISTORY_SEARCH_AUTO_ENABLED"},
				{Path: "tools.history_search.auto.max_per_turn", Label: "Max Per Turn", Description: "Maximum number of automatic history recall exposures per turn.", Type: "int", LiveApply: true, Env: "GODEX_TOOLS_HISTORY_SEARCH_AUTO_MAX_PER_TURN"},
				{Path: "tools.history_search.auto.default_scope", Label: "Default Scope", Description: "Default automatic recall scope. all_archives is intended for explicit requests only.", Type: "string", LiveApply: true, Env: "GODEX_TOOLS_HISTORY_SEARCH_AUTO_DEFAULT_SCOPE", Options: []string{"current_session", "session_archive", "all_archives"}},
				{Path: "tools.history_search.auto.allow_archive_on_clear", Label: "Allow Archive On Clear", Description: "Permit automatic recall to expand to session archives when active history is unavailable.", Type: "bool", LiveApply: true, Env: "GODEX_TOOLS_HISTORY_SEARCH_AUTO_ALLOW_ARCHIVE_ON_CLEAR"},
				{Path: "tools.history_search.auto.allow_archive_on_compact", Label: "Allow Archive On Compact", Description: "Permit automatic recall to expand to session archives after conversation compaction.", Type: "bool", LiveApply: true, Env: "GODEX_TOOLS_HISTORY_SEARCH_AUTO_ALLOW_ARCHIVE_ON_COMPACT"},
				{Path: "tools.history_search.auto.allow_all_archives_automatic", Label: "Allow All Archives Automatically", Description: "Permit weak automatic exposure to use all_archives. Leave disabled unless you explicitly want broad recall.", Type: "bool", LiveApply: true, Env: "GODEX_TOOLS_HISTORY_SEARCH_AUTO_ALLOW_ALL_ARCHIVES_AUTOMATIC"},
				{Path: "tools.history_search.auto.min_score", Label: "Min Score", Description: "Minimum score required before weak automatic history recall is exposed.", Type: "int", LiveApply: true, Env: "GODEX_TOOLS_HISTORY_SEARCH_AUTO_MIN_SCORE"},
				{Path: "tools.history_search.cues.explicit", Label: "Explicit Cues", Description: "Comma-separated phrases that strongly indicate the user explicitly wants history recall.", Type: "string_list", LiveApply: true, Env: "GODEX_TOOLS_HISTORY_SEARCH_CUES_EXPLICIT"},
				{Path: "tools.history_search.cues.implicit", Label: "Implicit Cues", Description: "Comma-separated softer phrases that suggest prior-conversation dependence.", Type: "string_list", LiveApply: true, Env: "GODEX_TOOLS_HISTORY_SEARCH_CUES_IMPLICIT"},
				{Path: "tools.history_search.blocks.session_sources", Label: "Blocked Session Sources", Description: "Comma-separated session sources that should not auto-expose history recall.", Type: "string_list", LiveApply: true, Env: "GODEX_TOOLS_HISTORY_SEARCH_BLOCKS_SESSION_SOURCES"},
			},
		},
		{
			ID:          "tools-permissions",
			Label:       "Tools / Permissions",
			Description: "Execution guardrails and approval policy for high-risk tool calls.",
			Fields: []FieldSchema{
				{Path: "tools.permissions.block_automation_mutations", Label: "Block Automation Mutations", Description: "Deny cron, heartbeat, and tool bundle mutations during active automation runs.", Type: "bool", LiveApply: true, Env: "GODEX_TOOLS_PERMISSIONS_BLOCK_AUTOMATION_MUTATIONS"},
				{Path: "tools.permissions.interactive_approval_enabled", Label: "Interactive Approval Enabled", Description: "Require approval before selected remote sessions can run high-risk tools.", Type: "bool", LiveApply: true, Env: "GODEX_TOOLS_PERMISSIONS_INTERACTIVE_APPROVAL_ENABLED"},
				{Path: "tools.permissions.interactive_approval_mode", Label: "Approval Mode", Description: "manual keeps pending approvals; review runs a reviewer subagent first; yolo auto-approves protected remote tool calls.", Type: "string", LiveApply: true, Env: "GODEX_TOOLS_PERMISSIONS_INTERACTIVE_APPROVAL_MODE", Options: []string{"manual", "review", "yolo"}},
				{Path: "tools.permissions.pending_ttl_seconds", Label: "Pending Approval TTL", Description: "Seconds before an unanswered approval request expires.", Type: "int", LiveApply: true, Env: "GODEX_TOOLS_PERMISSIONS_PENDING_TTL_SECONDS"},
				{Path: "tools.permissions.interactive_approval_sources", Label: "Approval Sources", Description: "Comma-separated remote sources subject to interactive approval. Typical values: web, gateway, feishu, weixin.", Type: "string_list", LiveApply: true, Env: "GODEX_TOOLS_PERMISSIONS_INTERACTIVE_APPROVAL_SOURCES"},
				{Path: "tools.permissions.interactive_approval_tools", Label: "Approval Tools", Description: "Comma-separated tool names that require approval when called from the configured sources.", Type: "string_list", LiveApply: true, Env: "GODEX_TOOLS_PERMISSIONS_INTERACTIVE_APPROVAL_TOOLS"},
				{Path: "tools.permissions.trusted_path_prefixes", Label: "Trusted Path Prefixes", Description: "Comma-separated path prefixes that bypass interactive approval for write/edit/install operations in remote sessions.", Type: "string_list", LiveApply: true, Env: "GODEX_TOOLS_PERMISSIONS_TRUSTED_PATH_PREFIXES"},
				{Path: "tools.permissions.trusted_command_prefixes", Label: "Trusted Command Prefixes", Description: "Comma-separated shell command prefixes that bypass interactive approval for bash/background_run when declared paths are also trusted.", Type: "string_list", LiveApply: true, Env: "GODEX_TOOLS_PERMISSIONS_TRUSTED_COMMAND_PREFIXES"},
			},
		},
		{
			ID:          "media-moonshot",
			Label:       "Media / Moonshot",
			Description: "Optional Moonshot file-extract preprocessing for documents and OCR.",
			Fields: []FieldSchema{
				{Path: "media.moonshot.enabled", Label: "Enabled", Description: "Enable Moonshot file-extract preprocessing for supported attachments.", Type: "bool", LiveApply: true, Env: "GODEX_MEDIA_MOONSHOT_ENABLED"},
				{Path: "media.moonshot.base_url", Label: "Base URL", Description: "Moonshot OpenAI-compatible base URL for file APIs.", Type: "string", LiveApply: true, Env: "GODEX_MEDIA_MOONSHOT_BASE_URL"},
				{Path: "media.moonshot.api_key", Label: "API Key", Description: "Moonshot API key for media preprocessing.", Type: "string", Secret: true, LiveApply: true, Env: "GODEX_MEDIA_MOONSHOT_API_KEY"},
			},
		},
		{
			ID:          "media-document",
			Label:       "Media / Documents",
			Description: "Document extraction defaults and local PDF fallback.",
			Fields: []FieldSchema{
				{Path: "media.document.max_chars", Label: "Max Chars", Description: "Maximum document characters injected into one model request before truncation.", Type: "int", LiveApply: true, Env: "GODEX_MEDIA_DOCUMENT_MAX_CHARS"},
				{Path: "media.document.pdftotext_path", Label: "pdftotext Path", Description: "Local pdftotext binary used when Moonshot file-extract is unavailable.", Type: "string", LiveApply: true, Env: "GODEX_MEDIA_DOCUMENT_PDFTOTEXT_PATH"},
			},
		},
		{
			ID:          "media-ocr",
			Label:       "Media / OCR",
			Description: "Image OCR mode and local tesseract fallback.",
			Fields: []FieldSchema{
				{Path: "media.ocr.mode", Label: "Mode", Description: "auto, moonshot, tesseract, or disabled.", Type: "string", LiveApply: true, Env: "GODEX_MEDIA_OCR_MODE", Options: []string{"auto", "moonshot", "tesseract", "disabled"}},
				{Path: "media.ocr.tesseract_path", Label: "Tesseract Path", Description: "Local tesseract binary for OCR fallback.", Type: "string", LiveApply: true, Env: "GODEX_MEDIA_OCR_TESSERACT_PATH"},
				{Path: "media.ocr.max_chars", Label: "Max Chars", Description: "Maximum OCR text injected into one model request before truncation.", Type: "int", LiveApply: true, Env: "GODEX_MEDIA_OCR_MAX_CHARS"},
			},
		},
		{
			ID:          "media-audio",
			Label:       "Media / Audio",
			Description: "Local audio transcription pipeline based on ffmpeg and whisper.cpp.",
			Fields: []FieldSchema{
				{Path: "media.audio.enabled", Label: "Enabled", Description: "Enable local audio transcription preprocessing.", Type: "bool", LiveApply: true, Env: "GODEX_MEDIA_AUDIO_ENABLED"},
				{Path: "media.audio.ffmpeg_path", Label: "ffmpeg Path", Description: "Local ffmpeg binary used for decoding and segmenting audio.", Type: "string", LiveApply: true, Env: "GODEX_MEDIA_AUDIO_FFMPEG_PATH"},
				{Path: "media.audio.ffprobe_path", Label: "ffprobe Path", Description: "Local ffprobe binary used for media inspection.", Type: "string", LiveApply: true, Env: "GODEX_MEDIA_AUDIO_FFPROBE_PATH"},
				{Path: "media.audio.whisper_cpp_path", Label: "whisper.cpp Path", Description: "whisper.cpp CLI executable used for transcription.", Type: "string", LiveApply: true, Env: "GODEX_MEDIA_AUDIO_WHISPER_CPP_PATH"},
				{Path: "media.audio.whisper_model_path", Label: "whisper.cpp Model Path", Description: "Local model file consumed by whisper.cpp.", Type: "string", LiveApply: true, Env: "GODEX_MEDIA_AUDIO_WHISPER_MODEL_PATH"},
				{Path: "media.audio.max_chars", Label: "Max Chars", Description: "Maximum transcript characters injected into one model request before truncation.", Type: "int", LiveApply: true, Env: "GODEX_MEDIA_AUDIO_MAX_CHARS"},
			},
		},
		{
			ID:          "media-video",
			Label:       "Media / Video",
			Description: "Local video summarization defaults based on transcript + keyframes.",
			Fields: []FieldSchema{
				{Path: "media.video.enabled", Label: "Enabled", Description: "Enable local video preprocessing.", Type: "bool", LiveApply: true, Env: "GODEX_MEDIA_VIDEO_ENABLED"},
				{Path: "media.video.keyframe_interval_seconds", Label: "Keyframe Interval Seconds", Description: "Preferred spacing between extracted keyframes.", Type: "int", LiveApply: true, Env: "GODEX_MEDIA_VIDEO_KEYFRAME_INTERVAL_SECONDS"},
				{Path: "media.video.max_frames", Label: "Max Frames", Description: "Maximum number of keyframes sent alongside a video summary.", Type: "int", LiveApply: true, Env: "GODEX_MEDIA_VIDEO_MAX_FRAMES"},
			},
		},
		{
			ID:          "channels-feishu",
			Label:       "Channel / Feishu",
			Description: "First-party Feishu/Lark runtime configuration.",
			Fields: []FieldSchema{
				{Path: "channels.feishu.enabled", Label: "Enabled", Description: "Enable the Feishu/Lark channel.", Type: "bool", LiveApply: true, Env: "FEISHU_ENABLED"},
				{Path: "channels.feishu.app_id", Label: "App ID", Description: "Feishu/Lark app ID.", Type: "string", Secret: true, LiveApply: true, Env: "FEISHU_APP_ID"},
				{Path: "channels.feishu.app_secret", Label: "App Secret", Description: "Feishu/Lark app secret.", Type: "string", Secret: true, LiveApply: true, Env: "FEISHU_APP_SECRET"},
				{Path: "channels.feishu.domain", Label: "Domain", Description: "Use lark or feishu API domain.", Type: "string", LiveApply: true, Env: "FEISHU_DOMAIN", Options: []string{"lark", "feishu"}},
			},
		},
		{
			ID:          "channels-weixin",
			Label:       "Channel / Weixin",
			Description: "First-party Weixin/iLink runtime configuration.",
			Fields: []FieldSchema{
				{Path: "channels.weixin.enabled", Label: "Enabled", Description: "Enable the Weixin/iLink channel.", Type: "bool", LiveApply: true, Env: "WEIXIN_ENABLED"},
				{Path: "channels.weixin.base_url", Label: "Base URL", Description: "Weixin iLink HTTP API base URL.", Type: "string", LiveApply: true, Env: "WEIXIN_BASE_URL"},
				{Path: "channels.weixin.cdn_base_url", Label: "CDN Base URL", Description: "Weixin CDN base URL used for media upload/download in later phases.", Type: "string", LiveApply: true, Env: "WEIXIN_CDN_BASE_URL"},
				{Path: "channels.weixin.account_id", Label: "Account ID", Description: "Logical local account bucket for persisted iLink credentials.", Type: "string", LiveApply: true, Env: "WEIXIN_ACCOUNT_ID"},
				{Path: "channels.weixin.allow_from", Label: "Allow From", Description: "Optional allowlist of iLink user IDs. Empty or * allows all senders.", Type: "string_list", LiveApply: true, Env: "WEIXIN_ALLOW_FROM"},
				{Path: "channels.weixin.route_tag", Label: "Route Tag", Description: "Optional metadata tag attached to inbound sessions from Weixin.", Type: "string", LiveApply: true, Env: "WEIXIN_ROUTE_TAG"},
				{Path: "channels.weixin.long_poll_timeout_ms", Label: "Long Poll Timeout Ms", Description: "Requested long-poll hold timeout in milliseconds.", Type: "int", LiveApply: true, Env: "WEIXIN_LONG_POLL_TIMEOUT_MS"},
				{Path: "channels.weixin.proxy", Label: "Proxy", Description: "Optional HTTP(S) proxy URL used for iLink API requests.", Type: "string", LiveApply: true, Env: "WEIXIN_PROXY"},
			},
		},
	}
}
